### ISSUE TITLE
Competition

### ISSUE THREAD

**Issue by LykeStuurman** [richelbilderbeek/pbdmms#46] opened 2016-11-18 14:25 UTC
Al een code coverage van 80%! volgens mij moet Kees maandag de koffie gaan halen....gheghe
@richelbilderbeek 
@Lumphie 
@JorikdeBoer

**Comment by richelbilderbeek** [comment] 2016-11-18 14:31
You suggest for #5 to use a rule `Kees should always fetch coffee`?

**Comment by LykeStuurman** [comment] 2016-11-18 14:37
I suggest that the person with the lowest code coverage should always fetch coffee.

**Comment by richelbilderbeek** [comment] 2016-11-18 14:38
At the moment, that is you... you acknowledge that?

**Comment by LykeStuurman** [comment] 2016-11-18 14:44
Not anymore!!

**Comment by richelbilderbeek** [comment] 2016-11-18 14:50
Well done. You consider a failing build and/or OCLint unimportant in this decision?

**Comment by LykeStuurman** [comment] 2016-11-18 14:54
No, you are right, that is important. So who do you think should fetch coffee at the moment?

**Comment by richelbilderbeek** [comment] 2016-11-18 14:57
It's hard to reach consensus on this, as 41 issues ago we started looking for it, see #5

**Comment by LykeStuurman** [comment] 2016-11-18 15:50
too bad richel. I am nr 500! @richelbilderbeek

**Comment by richelbilderbeek** [comment] 2016-11-18 15:53
I wanted to offer that people that push the 500th build should always bring coffee...

**Comment by richelbilderbeek** [comment] 2016-11-19 11:14
There *is* a strong sentiment for letting people breaking the `master` fetching coffee...

![koffievoorrichel](https://cloud.githubusercontent.com/assets/2098230/20455043/abe77c80-ae51-11e6-8ba9-1c68d7338a0b.png)

**Comment by LykeStuurman** [comment] 2016-11-19 13:45
well.. it is a good motivation to get it working again!

**Comment by richelbilderbeek** [comment] 2016-11-19 14:06
We are sure you won't let the team down too often :sunglasses:

**Comment by richelbilderbeek** [comment] 2016-11-20 15:42
I close this Issue as it is a duplicate of #5

**Closed by richelbilderbeek** 2016-11-20 15:42 UTC
